// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace no_music_no_desire
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int contextMenuMainListView = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int loginCancelButton = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int loginExecuteButton = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int loginLogoutSwitchButton = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int loginOrLogoutLabel = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int openAlbumsButton = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int openArtistsButton = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int openListsButton = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int passwordEntry = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int tableLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int tableRow1 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int tableRow2 = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int tableRow3 = 2131034120;
			
			// aapt resource value: 0x7f050012
			public const int tableRow4 = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int textOnlyLayoutText = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int textView11 = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int textView12 = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int textView13 = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int textView14 = 2131034118;
			
			// aapt resource value: 0x7f050014
			public const int textView18 = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int updateSongsButton = 2131034129;
			
			// aapt resource value: 0x7f050004
			public const int userNameEntry = 2131034116;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ArtistsList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContextMenu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TextOnlyLayout = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Password = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int UserName = 2130968578;
			
			private String()
			{
			}
		}
	}
}
